# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: test_auto_docker_image
    permissions:
     id-token: write
     contents: read
    
    steps:
    #- name: 'Google auth'
     # uses: 'google-github-actions/auth@v1'
      #with:
       # project_id: 'logical-zephyr-423609-u7'
        #workload_identity_provider: "projects/30728498820/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions"
        #create_credentials_file: true
        #service_account: "svc-uat1@logical-zephyr-423609-u7.iam.gserviceaccount.com"
        #token_format: "access_token"
        #access_token_lifetime: "120s"
        
    - name: 'Google auth 2'
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account: "git-hub-action@logical-zephyr-423609-u7.iam.gserviceaccount.com"
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY_NEW }}
        project_id: 'logical-zephyr-423609-u7'
        export_default_credentials: true
        
        #token_format: "access_token"
        #access_token_lifetime: "120s"
         
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: | 
       mvn -B package --file pom.xml
       mkdir staging && cp target/*.jar staging

    - name: Persist worflow data as artifact
      uses: actions/upload-artifact@v2
      with:
       name: github-actions-artifact
       path: staging

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
       gcloud auth configure-docker --quiet
       gcloud auth configure-docker us-docker.pkg.dev --quiet
    
    #- name: Push Docker Image to Container Registery
     # env:
      # GIT_TAG: v0.1.0
      #run: |-
       #docker tag $IMAGE_NAME:latest gcr.io/logical-zephyr-423609-u7/$IMAGE_NAME:latest 
       #docker tag $IMAGE_NAME:latest gcr.io/logical-zephyr-423609-u7/$IMAGE_NAME:$GIT_TAG
       #docker push gcr.io/logical-zephyr-423609-u7/$IMAGE_NAME:latest
       #docker push gcr.io/logical-zephyr-423609-u7/$IMAGE_NAME:$GIT_TAG

       
    - name: Push Docker Image to artifactory Registery
      env:
       GIT_TAG: v0.1.0
      run: |-
       docker tag $IMAGE_NAME:latest us-docker.pkg.dev/logical-zephyr-423609-u7/$IMAGE_NAME:latest 
       docker tag $IMAGE_NAME:latest us-docker.pkg.dev/logical-zephyr-423609-u7/$IMAGE_NAME:$GIT_TAG
       docker push us-docker.pkg.dev/logical-zephyr-423609-u7/$IMAGE_NAME:latest
       docker push us-docker.pkg.dev/logical-zephyr-423609-u7/$IMAGE_NAME:$GIT_TAG
